apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: counter-deployment
spec:
  selector:
    matchLabels:
      app: counter
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
        - name: counter
          image: rameshkumarverma/counter-app:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9099 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: counter-ssvc
spec:
  selector:
    app: counter
  ports:
    - protocol: "TCP"
      port: 9099 # The port that the service is running on in the cluster
      targetPort: 9099 # The port exposed by the service
  type: NodePort # type of the service.
